# Generated by Django 4.0.3 on 2022-05-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_image',
            field=models.ImageField(default='none', upload_to='images/'),
        ),
    ]
