# Generated by Django 4.0.3 on 2022-05-28 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cause', '0002_alter_cause_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='parish',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
