# Generated by Django 4.0.3 on 2022-05-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projectimages_image_projectvideos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectImages',
            new_name='ProjectImage',
        ),
        migrations.RenameModel(
            old_name='ProjectVideos',
            new_name='ProjectVideo',
        ),
    ]
