# Generated by Django 4.0.3 on 2022-03-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=60)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=225)),
            ],
        ),
    ]
